[project]
name = "callsight-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robotframework>=7.2.2",
    "robotframework-browser>=19.4.0",
]
